# Generated by Django 6.1.1 on 2026-09-22 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("jobs", "0011_jobs_belong_to_a_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.CharField(
                        help_text='Which agent called it, such as "producer".',
                        max_length=50,
                    ),
                ),
                ("tool", models.CharField(max_length=50)),
                (
                    "call_id",
                    models.CharField(
                        help_text="The model's id for the call, which pairs it with its result.",
                        max_length=200,
                    ),
                ),
                ("arguments", models.JSONField()),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        help_text="What the tool handed back to the agent. Blank until it finishes.",
                    ),
                ),
                ("finished", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="The job the tool worked on. Blank for a tool that works on no job.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="jobs.job",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="chat.session",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "call_id"), name="one_checkpoint_per_call"
                    )
                ],
            },
        ),
    ]
