# Generated by Django 6.1.1 on 2026-09-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_checkpoint_finish_time_and_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolcall",
            name="observation_id",
            field=models.CharField(
                blank=True,
                help_text="Its latest run's own ID in that trace.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="toolcall",
            name="trace_id",
            field=models.CharField(
                blank=True,
                help_text="The Langfuse trace its latest run is in, so a scene step it started, run elsewhere, is traced inside it. Blank when tracing is off.",
                max_length=32,
            ),
        ),
    ]
