# Generated by Django 6.1.1 on 2026-09-18 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0002_job_page_text_productphoto_activityentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose", models.CharField(max_length=50)),
                ("provider", models.CharField(max_length=30)),
                ("model", models.CharField(max_length=100)),
                ("attempt", models.PositiveSmallIntegerField()),
                ("handoff", models.JSONField()),
                ("output", models.JSONField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField()),
                ("decision", models.CharField(blank=True, max_length=50)),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="The one-sentence judgement, for judgements.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_calls",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
