# Generated by Django 6.1.1 on 2026-09-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcall",
            name="images",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="The pictures shown with the handoff: each one's label and file-store key.",
            ),
        ),
    ]
