# Generated by Django 6.1.1 on 2026-09-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0002_modelcall_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcall",
            name="characters",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Characters spoken, for voice models billed by them.",
                null=True,
            ),
        ),
    ]
