# Generated by Django 6.1.1 on 2026-09-22 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_checkpoints"),
        ("gateway", "0003_modelcall_characters"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcall",
            name="tool_call",
            field=models.ForeignKey(
                blank=True,
                help_text="The tool call this was made for. Blank for an agent's own turns.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="model_calls",
                to="agents.toolcall",
            ),
        ),
    ]
