# Generated by Django 6.1.1 on 2026-09-22 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("gateway", "0004_modelcall_tool_call"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcall",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="The session it was for, so a session's whole cost adds up. Blank only for calls made before sessions existed.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="model_calls",
                to="chat.session",
            ),
        ),
    ]
