# Generated by Django 6.1.1 on 2026-09-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0006_modelcall_audio_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcall",
            name="video_seconds",
            field=models.FloatField(
                blank=True,
                help_text="Seconds of video made, for models billed by them.",
                null=True,
            ),
        ),
    ]
