# Generated by Django 6.1.1 on 2026-09-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0007_modelcall_video_seconds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelcall",
            name="audio_seconds",
            field=models.FloatField(
                blank=True,
                help_text="Seconds of audio heard or made, for models billed by them.",
                null=True,
            ),
        ),
    ]
