# Generated by Django 6.1.1 on 2026-09-20 23:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Taken from the user's first message, until they rename it. Blank until they have said something.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seq",
                    models.PositiveIntegerField(
                        help_text="1, 2, 3... within the session, in the order they were said. What a poll asks for what has happened since."
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("agent", "Agent")], max_length=10
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="Blank when the message only carries files.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.session",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "seq"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="1, 2, 3... in the order shown."
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("picture", "Picture"),
                            ("sound", "Sound"),
                            ("video", "Video"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.CharField(
                        help_text="Key in the file store.", max_length=500
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "ordering": ["message", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "position"),
                        name="one_attachment_per_position",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("session", "seq"), name="one_message_per_seq"
            ),
        ),
    ]
