# Generated by Django 6.1.1 on 2026-09-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="producer_running",
            field=models.BooleanField(
                default=False, help_text="A producer should be working in this session."
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="producer_seen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The producer's heartbeat. A producer that is running but hasn't been seen for PRODUCER_DEAD_AFTER_SECONDS has died.",
                null=True,
            ),
        ),
    ]
