# Generated by Django 6.1.1 on 2026-09-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_producer_heartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="trace_id",
            field=models.CharField(
                blank=True,
                help_text="The Langfuse trace of the agent's work on the user's message, which each time it works on it adds to. Blank when not traced.",
                max_length=32,
            ),
        ),
    ]
