# Generated by Django 6.1.1 on 2026-10-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_message_trace_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("problem", "Problem"), ("info", "Info")],
                help_text="How a notice is shown. Blank for the user's and the agent's messages.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("agent", "Agent"), ("notice", "Notice")],
                max_length=10,
            ),
        ),
    ]
