# Generated by Django 6.1.1 on 2026-09-18 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="page_text",
            field=models.TextField(
                blank=True, help_text="The page's visible text, exactly as read."
            ),
        ),
        migrations.CreateModel(
            name="ProductPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("source_url", models.URLField(max_length=2000)),
                (
                    "file",
                    models.CharField(
                        help_text="Key in the file store.", max_length=500
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["job", "position"],
            },
        ),
        migrations.CreateModel(
            name="ActivityEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seq",
                    models.PositiveIntegerField(
                        help_text="1, 2, 3... within the job, in the order written."
                    ),
                ),
                ("message", models.TextField()),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activity entries",
                "ordering": ["job", "seq"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "seq"), name="one_entry_per_seq"
                    )
                ],
            },
        ),
    ]
