# Generated by Django 6.1.1 on 2026-09-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_page_text_productphoto_activityentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="page_html_key",
            field=models.CharField(
                blank=True,
                help_text="Key in the file store of the page's original HTML, exactly as served.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="page_text",
            field=models.TextField(
                blank=True,
                help_text="The words a visitor sees, then the product data the page declares for search engines. Model calls read this.",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("reading_page", "Reading Page"),
                    ("page_read", "Page Read"),
                    ("needs_working_link", "Needs Working Link"),
                    ("needs_product_photos", "Needs Product Photos"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
