# Generated by Django 6.1.1 on 2026-09-18 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_waits_for_the_user_and_keeps_page_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="brand_colours",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='The brand colours from the plan, as "#RRGGBB".',
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("reading_page", "Reading Page"),
                    ("page_read", "Page Read"),
                    ("planning", "Planning"),
                    ("planned", "Planned"),
                    ("needs_working_link", "Needs Working Link"),
                    ("needs_product_photos", "Needs Product Photos"),
                    ("needs_answer", "Needs Answer"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productphoto",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Where the page had it. Blank if the user uploaded it.",
                max_length=2000,
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("working_link", "Working Link"),
                            ("product_photos", "Product Photos"),
                            ("producer", "Producer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question", models.TextField()),
                (
                    "reason",
                    models.TextField(
                        help_text="One sentence on why the job had to ask."
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        blank=True,
                        help_text="The user's words, the new link, or the photos they uploaded.",
                    ),
                ),
                ("asked_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["job", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("answered_at__isnull", True)),
                        fields=("job",),
                        name="one_open_question_per_job",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="1, 2, 3... in the order they play."
                    ),
                ),
                (
                    "line",
                    models.TextField(help_text="What the person says in this scene."),
                ),
                (
                    "slot_seconds",
                    models.PositiveSmallIntegerField(
                        help_text="How long the scene lasts."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("planned", "Planned")],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["job", "number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "number"), name="one_scene_per_number"
                    )
                ],
            },
        ),
    ]
