# Generated by Django 6.1.1 on 2026-09-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_questions_for_jobs_already_waiting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="brand_colours",
        ),
    ]
