# Generated by Django 6.1.1 on 2026-09-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_job_drops_brand_colours"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="product_colour",
            field=models.CharField(
                blank=True,
                help_text="The colour the ad shows the product in, picked by the producer from the product photos.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="productphoto",
            name="shows_product_colour",
            field=models.BooleanField(
                default=False,
                help_text="Shows the product in the job's product colour, so the ad can use it.",
            ),
        ),
    ]
