# Generated by Django 6.1.1 on 2026-09-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_product_colour"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productphoto",
            constraint=models.UniqueConstraint(
                fields=("job", "position"), name="one_photo_per_position"
            ),
        ),
    ]
