# Generated by Django 6.1.1 on 2026-09-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_one_photo_per_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scene",
            name="slot_seconds",
        ),
        migrations.AddField(
            model_name="job",
            name="length_choice",
            field=models.CharField(
                blank=True,
                choices=[("shorten", "Shorten"), ("keep_longer", "Keep Longer")],
                help_text="What the user chose when the script didn't fit the target length.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="person_looks",
            field=models.TextField(
                blank=True,
                help_text="The producer's description of the person the portrait shows.",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="person_voice",
            field=models.TextField(
                blank=True,
                help_text="The producer's description of the person's voice.",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="shorten_tries",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Times the producer has shortened the script since the user chose to.",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="The choices offered. Empty means a typed answer.",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="scene",
            field=models.ForeignKey(
                blank=True,
                help_text="The scene whose line the question is about, if any.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="jobs.scene",
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="fact_checked",
            field=models.BooleanField(
                default=False,
                help_text="The line passed the fact check, or the user kept it.",
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="fact_problems",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Why the fact check failed this line each time, oldest first. Two rewrites are tried before the user is asked.",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("reading_page", "Reading Page"),
                    ("page_read", "Page Read"),
                    ("planning", "Planning"),
                    ("planned", "Planned"),
                    ("making_person", "Making Person"),
                    ("checking_plan", "Checking Plan"),
                    ("ready_to_render", "Ready To Render"),
                    ("needs_working_link", "Needs Working Link"),
                    ("needs_product_photos", "Needs Product Photos"),
                    ("needs_answer", "Needs Answer"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("working_link", "Working Link"),
                    ("product_photos", "Product Photos"),
                    ("producer", "Producer"),
                    ("unclear_page", "Unclear Page"),
                    ("fact_check", "Fact Check"),
                    ("length", "Length"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProducedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("portrait", "Portrait"), ("voice", "Voice")],
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "file",
                    models.CharField(
                        help_text="Key in the file store: the portrait, or the voice's measuring sample.",
                        max_length=500,
                    ),
                ),
                ("voice_id", models.CharField(blank=True, max_length=200)),
                (
                    "words_per_second",
                    models.FloatField(
                        blank=True,
                        help_text="The voice's measured speaking speed.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produced",
                        to="jobs.job",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank when it belongs to the whole job.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produced",
                        to="jobs.scene",
                    ),
                ),
            ],
            options={
                "ordering": ["job", "kind", "version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "scene", "kind", "version"),
                        name="one_item_per_version",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
    ]
