# Generated by Django 6.1.1 on 2026-09-19 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_person_and_planning_checks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produceditem",
            name="file",
            field=models.CharField(
                blank=True,
                help_text="Key in the file store: the portrait, or the voice's measuring sample. Blank for a voice not measured yet.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="scene",
            field=models.ForeignKey(
                blank=True,
                help_text="The scene whose line the question is about, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="jobs.scene",
            ),
        ),
    ]
