# Generated by Django 6.1.1 on 2026-09-20 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("jobs", "0010_keep_questions_and_unmeasured_voices"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="The session this job was asked for in. Blank only for jobs started before sessions existed; #15 has the agent make every job inside a session.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="chat.session",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="variant_of",
            field=models.ForeignKey(
                blank=True,
                help_text="The job in the same session this one varies, so the two can be compared. Variants are siblings, not versions.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="jobs.job",
            ),
        ),
    ]
