# Generated by Django 6.1.1 on 2026-09-24 02:02

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

# The statuses removed here, which only the fixed pipeline gave a job.
REMOVED_STATUSES = ["needs_working_link", "needs_product_photos", "needs_answer", "failed"]


def label_how_far_they_got(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Give each job left with a removed status the label for how far it got."""
    Job = apps.get_model("jobs", "Job")
    for job in Job.objects.filter(status__in=REMOVED_STATUSES):
        if job.scenes.exists():
            job.status = "planned"
        elif job.status != "needs_working_link" and (
            job.photos.exists() or job.status == "needs_product_photos"
        ):
            job.status = "page_read"
        else:
            job.status = "reading_page"
        job.save(update_fields=["status"])


def forget_pages_not_found_usable(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """A job's page now counts as found to show its product once it is stored, so only such
    a page may stay stored. The producer stored a page before checking it, and a job whose
    page wasn't found usable was left reading it."""
    Job = apps.get_model("jobs", "Job")
    Job.objects.filter(session__isnull=False, status__in=["queued", "reading_page"]).update(
        page_text="", page_html_key=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_jobs_belong_to_a_session"),
    ]

    operations = [
        migrations.RunPython(label_how_far_they_got, migrations.RunPython.noop),
        migrations.RunPython(forget_pages_not_found_usable, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="activityentry",
            name="one_entry_per_seq",
        ),
        migrations.RemoveConstraint(
            model_name="question",
            name="one_open_question_per_job",
        ),
        migrations.AlterField(
            model_name="job",
            name="page_html_key",
            field=models.CharField(
                blank=True,
                help_text="Key in the file store of the page's original HTML, exactly as served. Blank until the page has been found to show its product and its photos are kept.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("reading_page", "Reading Page"),
                    ("page_read", "Page Read"),
                    ("planning", "Planning"),
                    ("planned", "Planned"),
                    ("making_person", "Making Person"),
                    ("checking_plan", "Checking Plan"),
                    ("ready_to_render", "Ready To Render"),
                ],
                default="queued",
                help_text="A label for how far the job has got. Nothing reads it to decide what happens next: each tool decides that from what the job has.",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="question",
            name="job",
        ),
        migrations.RemoveField(
            model_name="question",
            name="scene",
        ),
        migrations.DeleteModel(
            name="ActivityEntry",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
