# Generated by Django 6.1.1 on 2026-09-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_jobs_belong_to_a_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="shorten_tries",
        ),
    ]
