# Generated by Django 6.1.1 on 2026-09-24 03:30

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

# The statuses removed here: nothing sets them since the fixed pipeline went.
REMOVED_STATUSES = ["planning", "making_person", "checking_plan"]


def label_how_far_they_got(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Give each job left with a removed status the label for how far it got."""
    Job = apps.get_model("jobs", "Job")
    for job in Job.objects.filter(status__in=REMOVED_STATUSES):
        job.status = "planned" if job.scenes.exists() else "page_read"
        job.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_remove_the_fixed_pipeline"),
    ]

    operations = [
        migrations.RunPython(label_how_far_they_got, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="job",
            name="shorten_tries",
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("reading_page", "Reading Page"),
                    ("page_read", "Page Read"),
                    ("planned", "Planned"),
                    ("ready_to_render", "Ready To Render"),
                ],
                default="queued",
                help_text="A label for how far the job has got. Nothing reads it to decide what happens next: each tool decides that from what the job has.",
                max_length=20,
            ),
        ),
    ]
