# Generated by Django 6.1.1 on 2026-09-24 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_checkpoint_finish_time_and_questions"),
        ("jobs", "0013_drop_what_nothing_sets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produceditem",
            name="file",
            field=models.CharField(
                blank=True,
                help_text="Key in the file store: the picture, or the voice's measuring sample. Blank for a voice not measured yet.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("portrait", "Portrait"),
                    ("voice", "Voice"),
                    ("starting_picture", "Starting Picture"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SceneStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("starting_picture", "Starting Picture")],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("stopped", "Stopped"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why it failed or was stopped."
                    ),
                ),
                (
                    "line",
                    models.TextField(
                        help_text="The scene's line when the step started."
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="What the producer asked for, beyond the line. Blank for nothing.",
                    ),
                ),
                (
                    "photo_reason",
                    models.TextField(
                        blank=True, help_text="Why that photo suits the line."
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        help_text="What the picture model was asked to make.",
                    ),
                ),
                (
                    "prompt_reason",
                    models.TextField(
                        blank=True, help_text="Why the prompt asks for that."
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        help_text="What the producer is told when the step finishes or fails. Blank while it runs.",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When it finished or failed. Blank while it runs.",
                        null=True,
                    ),
                ),
                (
                    "producer_read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the producer was first given the result. Until then the producer doesn't stop, so no result is lost.",
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="The product photo the starting picture was made from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="jobs.productphoto",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="jobs.scene",
                    ),
                ),
                (
                    "tool_call",
                    models.ForeignKey(
                        help_text="The tool call that started it, which its model calls are charged to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_steps",
                        to="agents.toolcall",
                    ),
                ),
            ],
            options={
                "ordering": ["started_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="produceditem",
            name="step",
            field=models.ForeignKey(
                blank=True,
                help_text="The scene step that made it. Blank for what belongs to the whole job.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produced",
                to="jobs.scenestep",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenestep",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "running")),
                fields=("scene", "kind"),
                name="one_running_step_per_scene_and_kind",
            ),
        ),
    ]
