# Generated by Django 6.1.1 on 2026-09-24 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_scene_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="produceditem",
            name="made_from",
            field=models.ForeignKey(
                blank=True,
                help_text="What it was made from: for a line's audio, the voice that spoke it; for a transcript, the audio it was heard in.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="jobs.produceditem",
            ),
        ),
        migrations.AddField(
            model_name="produceditem",
            name="seconds",
            field=models.FloatField(
                blank=True, help_text="How long the audio lasts.", null=True
            ),
        ),
        migrations.AddField(
            model_name="produceditem",
            name="text",
            field=models.TextField(
                blank=True, help_text="The transcript, exactly as it was heard."
            ),
        ),
        migrations.AddField(
            model_name="produceditem",
            name="words",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Each word heard, with when it starts and ends in seconds: [{"text", "start", "end"}, ...].',
            ),
        ),
        migrations.AddField(
            model_name="scenestep",
            name="made_from",
            field=models.ForeignKey(
                blank=True,
                help_text="What the step makes its item from, fixed when it starts: the voice that speaks a line's audio, or the audio a transcript is heard in.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="jobs.produceditem",
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="file",
            field=models.CharField(
                blank=True,
                help_text="Key in the file store: the picture, the line's audio, or the voice's measuring sample. Blank for a voice not measured yet, and for a transcript.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("portrait", "Portrait"),
                    ("voice", "Voice"),
                    ("starting_picture", "Starting Picture"),
                    ("line_audio", "Line Audio"),
                    ("transcript", "Transcript"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scenestep",
            name="kind",
            field=models.CharField(
                choices=[
                    ("starting_picture", "Starting Picture"),
                    ("line_audio", "Line Audio"),
                    ("transcript", "Transcript"),
                ],
                max_length=30,
            ),
        ),
    ]
