# Generated by Django 6.1.1 on 2026-09-25 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0015_line_audio_and_transcripts"),
    ]

    operations = [
        migrations.AddField(
            model_name="produceditem",
            name="picture",
            field=models.ForeignKey(
                blank=True,
                help_text="The starting picture a clip animates.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="jobs.produceditem",
            ),
        ),
        migrations.AddField(
            model_name="scenestep",
            name="picture",
            field=models.ForeignKey(
                blank=True,
                help_text="The starting picture a clip animates, fixed when it starts.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="jobs.produceditem",
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="file",
            field=models.CharField(
                blank=True,
                help_text="Key in the file store: the picture, the line's audio, the clip, or the voice's measuring sample. Blank for a voice not measured yet, and for a transcript.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("portrait", "Portrait"),
                    ("voice", "Voice"),
                    ("starting_picture", "Starting Picture"),
                    ("line_audio", "Line Audio"),
                    ("transcript", "Transcript"),
                    ("clip", "Clip"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="made_from",
            field=models.ForeignKey(
                blank=True,
                help_text="What it was made from: for a line's audio, the voice that spoke it; for a transcript, the audio it was heard in; for a clip, the audio it speaks.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="jobs.produceditem",
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="seconds",
            field=models.FloatField(
                blank=True, help_text="How long the audio or the clip lasts.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="scene",
            name="status",
            field=models.CharField(
                choices=[("planned", "Planned"), ("finished", "Finished")],
                default="planned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scenestep",
            name="kind",
            field=models.CharField(
                choices=[
                    ("starting_picture", "Starting Picture"),
                    ("line_audio", "Line Audio"),
                    ("transcript", "Transcript"),
                    ("clip", "Clip"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="scenestep",
            name="made_from",
            field=models.ForeignKey(
                blank=True,
                help_text="What the step makes its item from, fixed when it starts: the voice that speaks a line's audio, or the audio a transcript is heard in or a clip speaks.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="jobs.produceditem",
            ),
        ),
    ]
