# Generated by Django 6.1.1 on 2026-09-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0016_clips"),
    ]

    operations = [
        migrations.AddField(
            model_name="produceditem",
            name="cuts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='For a finished ad, each scene in the order it plays: its clip, the part of the clip kept, and where that part plays in the ad, in seconds: [{"scene", "clip", "clip_start", "clip_end", "start", "end"}, ...].',
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="file",
            field=models.CharField(
                blank=True,
                help_text="Key in the file store: the picture, the line's audio, the clip, the finished ad, or the voice's measuring sample. Blank for a voice not measured yet, and for a transcript.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("portrait", "Portrait"),
                    ("voice", "Voice"),
                    ("starting_picture", "Starting Picture"),
                    ("line_audio", "Line Audio"),
                    ("transcript", "Transcript"),
                    ("clip", "Clip"),
                    ("finished_ad", "Finished Ad"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="seconds",
            field=models.FloatField(
                blank=True,
                help_text="How long the audio, the clip or the finished ad lasts.",
                null=True,
            ),
        ),
    ]
