# Generated by Django 6.1.1 on 2026-09-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0017_finished_ad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produceditem",
            name="file",
            field=models.CharField(
                blank=True,
                help_text="Key in the file store: the picture, the line's audio, the clip, the finished ad, the music, or the voice's measuring sample. Blank for a voice not measured yet, and for a transcript.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("portrait", "Portrait"),
                    ("voice", "Voice"),
                    ("starting_picture", "Starting Picture"),
                    ("line_audio", "Line Audio"),
                    ("transcript", "Transcript"),
                    ("clip", "Clip"),
                    ("finished_ad", "Finished Ad"),
                    ("music", "Music"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="seconds",
            field=models.FloatField(
                blank=True,
                help_text="How long the audio, the clip, the finished ad or the music lasts.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="The transcript, exactly as it was heard, or what the music was asked to sound like.",
            ),
        ),
    ]
