# Generated by Django 6.1.1 on 2026-09-26 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0018_music"),
    ]

    operations = [
        migrations.AddField(
            model_name="produceditem",
            name="captions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='For a finished ad, the words drawn along its bottom as they were spoken, a few at a time, and when each shows, in seconds: [{"text", "start", "end"}, ...].',
            ),
        ),
        migrations.AlterField(
            model_name="produceditem",
            name="made_from",
            field=models.ForeignKey(
                blank=True,
                help_text="What it was made from: for a line's audio, the voice that spoke it; for a transcript, the audio it was heard in; for a clip, the audio it speaks; for a finished ad, the music under its voice.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="jobs.produceditem",
            ),
        ),
    ]
