# Generated by Django 6.1.1 on 2026-09-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0019_captions"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="overlay",
            field=models.TextField(
                blank=True,
                help_text="A few words drawn along the top of the picture while the scene plays, such as the price. Blank for none. Not fact checked yet.",
            ),
        ),
    ]
