# Generated by Django 6.1.1 on 2026-09-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0020_overlays"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="product_name",
            field=models.CharField(
                blank=True,
                help_text="The product's name as the ad says it, from the plan. At least one scene where the person talks to camera says it.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="shows",
            field=models.TextField(
                blank=True,
                help_text="What a B-roll scene shows, in plain words, while the person's voice says the line over it. Blank for a scene where the person talks to camera.",
            ),
        ),
        migrations.AddField(
            model_name="scenestep",
            name="motion_prompt",
            field=models.TextField(
                blank=True,
                help_text="For a B-roll scene's starting picture, how the video model is asked to move it. Blank for a talking scene, whose clips all move the same way.",
            ),
        ),
        migrations.AddField(
            model_name="scenestep",
            name="shows",
            field=models.TextField(
                blank=True,
                help_text="What the scene showed when the step started: blank for the person talking to camera.",
            ),
        ),
        migrations.AlterField(
            model_name="scene",
            name="fact_checked",
            field=models.BooleanField(
                default=False,
                help_text="The line, and what the scene shows, passed the fact check, or the user kept them.",
            ),
        ),
    ]
