# Generated by Django 6.1.1 on 2026-09-27 21:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0021_b_roll_scenes"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenestep",
            name="seen_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The step's heartbeat: when it was started, then every STEP_HEARTBEAT_SECONDS while it works. A running step that hasn't been seen for STEP_DEAD_AFTER_SECONDS has died, and no longer keeps its session busy.",
            ),
        ),
    ]
