# Generated by Django 6.1.1 on 2026-09-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0022_scenestep_seen_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="person_gender",
            field=models.CharField(
                blank=True,
                choices=[("man", "Man"), ("woman", "Woman")],
                help_text="What the person presents as, from the plan. Code puts it into both the portrait's prompt and the voice's description, so the two can't disagree. Blank for a job planned before it was asked, whose person is made from the words alone.",
                max_length=10,
            ),
        ),
    ]
