# Generated by Django 6.1.1 on 2026-09-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0023_job_person_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="product_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tiny", "Tiny"),
                    ("handheld", "Handheld"),
                    ("large", "Large"),
                ],
                help_text="How big the product is, from the plan. Code turns it into the pose every talking scene's starting picture and clip are asked for. Blank for a job planned before it was asked, which is posed as handheld, as every job was then.",
                max_length=20,
            ),
        ),
    ]
