# Generated by Django 6.1.1 on 2026-10-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0024_job_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="warnings",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Every notice posted while making this ad, each {level, text, at}, so an ad made with a fallback can be found after the chat has scrolled away.",
            ),
        ),
    ]
