# Generated by Django 6.1.1 on 2026-10-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0025_job_warnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="firecrawl",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Firecrawl\'s answers for the link read, kept so reading it again reuses them: {"url": link, "files": {"page": key in the file store}}. Empty until Firecrawl has answered.',
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="page_text_full",
            field=models.TextField(
                blank=True,
                help_text="Every word a visitor sees on the page, then its declared product data, other products' text included. Kept for debugging; no model call reads it.",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="page_text",
            field=models.TextField(
                blank=True,
                help_text="Only this product's own text: the sentences a model copied out of the page about it, each found on the page, then the product data the page declares for search engines. Model calls read this.",
            ),
        ),
    ]
