# Generated by Django 6.1.1 on 2026-10-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0026_page_text_full_and_firecrawl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="firecrawl",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Firecrawl\'s answers for the link read, kept so reading it again reuses them: {"url": link, "files": {"page", "marked", "product", "screenshot": key in the file store}, "picker_images": [[label, key], ...]}, each added as it arrives. Empty until Firecrawl has answered.',
            ),
        ),
    ]
