# Generated by Django 6.1.1 on 2026-10-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0027_firecrawl_answers_kept"),
    ]

    operations = [
        migrations.AddField(
            model_name="productphoto",
            name="has_face",
            field=models.BooleanField(
                default=False,
                help_text="Shows a stranger's face you could recognise. Yes too when noting it failed: such a photo is only used when no other shows what's needed.",
            ),
        ),
    ]
