# Generated by Django 6.1.1 on 2026-10-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0028_productphoto_has_face"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="broll_kind",
            field=models.CharField(
                blank=True,
                choices=[("does a job", "Does A Job"), ("showcase", "Showcase")],
                help_text='A B-roll scene\'s kind: "does a job" (the product does something you can see) or "showcase" (the product at its best). Blank for a talking scene, and for a B-roll scene planned before it was given.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="needs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='What a B-roll scene needs that the main photo can\'t show, each with the numbers of the photos that show it, such as [{"what": "the gel", "photos": [3, 5]}]. Empty when the main photo is enough.',
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="person_shown",
            field=models.CharField(
                blank=True,
                choices=[("no face", "No Face"), ("has face", "Has Face")],
                help_text="Whether a B-roll scene shows the presenter's face. Blank for a talking scene, and for a B-roll scene planned before it was given.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="result",
            field=models.TextField(
                blank=True,
                help_text='What you can see at the end of a "does a job" scene, which it ends on. Blank otherwise.',
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="usage",
            field=models.TextField(
                blank=True,
                help_text="How the product is used in a B-roll scene, from the page's \"how to use\". Blank when it isn't used, and for a talking scene.",
            ),
        ),
    ]
