# Generated by Django 6.1.1 on 2026-10-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0029_scene_broll_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="shortened_from",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="The lines this line was shortened from, oldest first, because their audio was too long for a B-roll clip. A starting picture made for one of them still suits it. Emptied when the line changes any other way.",
            ),
        ),
    ]
