# Generated by Django 6.1.1 on 2026-10-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0030_scene_shortened_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenestep",
            name="broll_kind",
            field=models.CharField(
                blank=True,
                choices=[("does a job", "Does A Job"), ("showcase", "Showcase")],
                help_text="The scene's B-roll kind when the step started.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scenestep",
            name="broll_result",
            field=models.TextField(
                blank=True,
                help_text="The result the scene ended on when the step started.",
            ),
        ),
        migrations.AddField(
            model_name="scenestep",
            name="needs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="What the scene needed that the main photo can't show when the step started.",
            ),
        ),
        migrations.AddField(
            model_name="scenestep",
            name="person_shown",
            field=models.CharField(
                blank=True,
                choices=[("no face", "No Face"), ("has face", "Has Face")],
                help_text="Whether the scene showed the presenter's face when the step started.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scenestep",
            name="pictures_sent",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='For a B-roll scene\'s starting picture, the pictures sent, in order, each with its job, such as [{"image": 1, "photo": 3, "job": "the product, only how it looks"}, {"image": 2, "portrait": true, "job": "the presenter"}]. Empty otherwise.',
            ),
        ),
        migrations.AddField(
            model_name="scenestep",
            name="usage",
            field=models.TextField(
                blank=True,
                help_text="How the scene used the product when the step started.",
            ),
        ),
        migrations.AddField(
            model_name="scenestep",
            name="way",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="For a B-roll scene's starting picture, how its clip is made: 1, from a starting picture made from the main photo. Blank for a talking scene, and for a B-roll scene planned before it had its B-roll labels.",
                null=True,
            ),
        ),
    ]
