# Generated by Django 6.1.1 on 2026-10-05 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0031_scenestep_broll_way"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenestep",
            name="picture_step",
            field=models.ForeignKey(
                blank=True,
                help_text="For a clip, the starting picture step it was made from, fixed when it starts: for a B-roll scene made way 3, it holds the example pictures and the prompt.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="jobs.scenestep",
            ),
        ),
        migrations.AlterField(
            model_name="scenestep",
            name="picture",
            field=models.ForeignKey(
                blank=True,
                help_text="The starting picture a clip animates, fixed when it starts. Blank for a B-roll scene made way 3, which has none.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="jobs.produceditem",
            ),
        ),
        migrations.AlterField(
            model_name="scenestep",
            name="way",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "From a starting picture"), (3, "From example pictures")],
                help_text="For a B-roll scene's starting picture, how its clip is made: 1, from a starting picture made from the main photo; 3, from example pictures, with no picture made. Blank for a talking scene, and for a B-roll scene planned before it had its B-roll labels.",
                null=True,
            ),
        ),
    ]
