# Generated by Django 6.1.1 on 2026-10-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0032_scenestep_picture_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hook", "Hook"),
                    ("problem", "Problem"),
                    ("product in action", "Product In Action"),
                    ("result", "Result"),
                    ("call to action", "Call To Action"),
                ],
                help_text="The part of the script the scene plays, in this order: hook, problem, product in action, result, call to action. Blank for a scene planned before it was given.",
                max_length=20,
            ),
        ),
    ]
