# Generated by Django 6.1.1 on 2026-10-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0032_scenestep_picture_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="script_format",
            field=models.CharField(
                blank=True,
                help_text='The structure the ad\'s body plays in, between its hook and its call to action, from the plan: such as "before and after" (jobs.planning.ScriptFormat). Blank for an ad planned before it was given.',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="part",
            field=models.CharField(
                blank=True,
                help_text='The part of the script the scene plays: "hook" first, "call to action" last, and between them the parts of the job\'s script format, in their order. Blank for a scene planned before it was given.',
                max_length=30,
            ),
        ),
    ]
