# Generated by Django 6.1.1 on 2026-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0033_script_format_and_scene_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="second_state",
            field=models.BooleanField(
                default=False,
                help_text="For a B-roll scene, whether it shows the second of two end states one claim needs, such as the second way a bag is carried, the first being the B-roll scene just before it.",
            ),
        ),
    ]
