# Generated by Django 6.1.1 on 2026-10-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0034_scene_second_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="product_name",
            field=models.CharField(
                blank=True,
                help_text="The product's name as the ad says it, from the plan. At least one line says it.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="scene",
            name="broll_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("does a job", "Does A Job"),
                    ("shows the problem", "Shows The Problem"),
                    ("showcase", "Showcase"),
                ],
                help_text='A B-roll scene\'s kind: "does a job" (the product does something you can see), "shows the problem" (the problem it fixes, before it is used) or "showcase" (the product at its best). Blank for a talking scene, and for a B-roll scene planned before it was given.',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scenestep",
            name="broll_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("does a job", "Does A Job"),
                    ("shows the problem", "Shows The Problem"),
                    ("showcase", "Showcase"),
                ],
                help_text="The scene's B-roll kind when the step started.",
                max_length=20,
            ),
        ),
    ]
